### ISSUE TITLE
TDD 應該先寫好一個測試案例，就要通過它

### ISSUE THREAD

**Issue by hatelove** [blackie1019/TDDDay2HomeWork#1]
TDD的過程，是先寫好一個最簡單的測試案例，然後就要用最簡單的 prod code 通過這個測試。

這跟 homework1 不一樣，不是要大家練習寫測試案例而已，而是練習 TDD 的過程。所以我還要看到你 test case + prod code 逐漸增加跟調整的 commit history

**Comment by blackie1019** [comment]
報告９１老師，很抱歉今天才有空寫作業。不過我有安照你說明ㄧ步步的補上我的開發過程並且一個段落就測試，直到通過我的所有測試。
但我蠻好奇這樣的開發方式是否還是要有最低線的Design(Interface跟Class等建好）才ㄧ步步完成，不然會不會在大型開發裡面會造成問題？

也感謝91哥幫我們一行一行看Code！
